# Generated by Django 3.0.5 on 2020-04-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='Paper_Title',
            field=models.CharField(help_text='Paper Title:', max_length=250),
        ),
    ]
