# Generated by Django 3.0.5 on 2020-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20200430_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='Paper_ID',
            field=models.AutoField(help_text='Paper ID:', primary_key=True, serialize=False),
        ),
    ]
