# Generated by Django 3.0.5 on 2020-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20200430_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='Paper_Content',
            field=models.BinaryField(default=0, help_text='Paper Content'),
        ),
    ]
