# Generated by Django 3.0.5 on 2020-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_auto_20200503_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='Paper_Content',
            field=models.BinaryField(default=0, help_text='Paper Content'),
        ),
    ]
