# Generated by Django 3.0.5 on 2020-04-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_ID',
            field=models.AutoField(help_text='Project ID:', primary_key=True, serialize=False),
        ),
    ]
