# Generated by Django 3.0.5 on 2020-04-30 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200430_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_Title',
            field=models.CharField(help_text='Project Title:', max_length=250),
        ),
    ]
