# Generated by Django 3.0.5 on 2020-04-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_ID', models.IntegerField(help_text='Project ID:', primary_key=True, serialize=False)),
                ('Project_Title', models.CharField(help_text='Project Title:', max_length=50)),
                ('Project_Description', models.CharField(help_text='Project Description:', max_length=560)),
                ('Project_Date', models.CharField(help_text='Date (mm/dd/yyyy):', max_length=10)),
            ],
        ),
    ]
