# Generated by Django 3.0.5 on 2020-04-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Paper_Content',
            field=models.BinaryField(default=0, help_text='Paper Content'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='Paper_ID',
            field=models.IntegerField(help_text='Paper ID:', primary_key=True, serialize=False),
        ),
    ]
