# Generated by Django 3.0.5 on 2020-04-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200424_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Paper_Content',
            field=models.FileField(default=0, help_text='Paper Content', upload_to=''),
        ),
    ]
